//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.30 at 11:36:10 PM TRT 
//


package com.guezey.gms.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="parkedCar" type="{http://guezey.com/gms/xml}car"/&gt;
 *         &lt;element name="parkingLot" type="{http://guezey.com/gms/xml}lot"/&gt;
 *         &lt;element name="inDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "parkedCar",
})
@XmlRootElement(name = "parkCarResponse")
public class ParkCarResponse {

    @XmlElement(required = true)
    protected CarXml parkedCar;

    /**
     * Gets the value of the parkedCar property.
     * 
     * @return
     *     possible object is
     *     {@link CarXml }
     *     
     */
    public CarXml getParkedCar() {
        return parkedCar;
    }

    /**
     * Sets the value of the parkedCar property.
     * 
     * @param value
     *     allowed object is
     *     {@link CarXml }
     *     
     */
    public void setParkedCar(CarXml value) {
        this.parkedCar = value;
    }


}
