//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.01 at 06:29:37 PM TRT 
//


package com.guezey.gms.xml.request;

import com.guezey.gms.xml.ParkingLotXml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="log" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="entry" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *                   &lt;element name="exit" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *                   &lt;element name="plate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="lot" type="{http://guezey.com/gms/xml}lot"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "message",
    "log"
})
@XmlRootElement(name = "listLogsResponse")
public class ListLogsResponse {

    @XmlElement(required = true)
    protected String message;
    @XmlElement(required = true)
    protected List<ListLogsResponse.Log> log;

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessage(String value) {
        this.message = value;
    }

    /**
     * Gets the value of the log property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the log property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLog().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ListLogsResponse.Log }
     * 
     * 
     */
    public List<ListLogsResponse.Log> getLog() {
        if (log == null) {
            log = new ArrayList<ListLogsResponse.Log>();
        }
        return this.log;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="entry" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
     *         &lt;element name="exit" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
     *         &lt;element name="plate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="lot" type="{http://guezey.com/gms/xml}lot"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "entry",
        "exit",
        "plate",
        "lot"
    })
    public static class Log {

        @XmlElement(required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar entry;
        @XmlElement(required = true, nillable = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar exit;
        @XmlElement(required = true)
        protected String plate;
        @XmlElement(required = true)
        protected ParkingLotXml lot;

        /**
         * Gets the value of the entry property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getEntry() {
            return entry;
        }

        /**
         * Sets the value of the entry property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setEntry(XMLGregorianCalendar value) {
            this.entry = value;
        }

        /**
         * Gets the value of the exit property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getExit() {
            return exit;
        }

        /**
         * Sets the value of the exit property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setExit(XMLGregorianCalendar value) {
            this.exit = value;
        }

        /**
         * Gets the value of the plate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlate() {
            return plate;
        }

        /**
         * Sets the value of the plate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlate(String value) {
            this.plate = value;
        }

        /**
         * Gets the value of the lot property.
         * 
         * @return
         *     possible object is
         *     {@link ParkingLotXml }
         *     
         */
        public ParkingLotXml getLot() {
            return lot;
        }

        /**
         * Sets the value of the lot property.
         * 
         * @param value
         *     allowed object is
         *     {@link ParkingLotXml }
         *     
         */
        public void setLot(ParkingLotXml value) {
            this.lot = value;
        }

    }

}
