//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.31 at 08:03:18 PM TRT 
//


package com.guezey.gms.xml.request;

import com.guezey.gms.xml.CarXml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="carToRegister" type="{http://guezey.com/gms/xml}car"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "carToRegister"
})
@XmlRootElement(name = "registerCarRequest")
public class RegisterCarRequest {

    @XmlElement(required = true)
    protected CarXml carToRegister;

    /**
     * Gets the value of the carToRegister property.
     * 
     * @return
     *     possible object is
     *     {@link CarXml }
     *     
     */
    public CarXml getCarToRegister() {
        return carToRegister;
    }

    /**
     * Sets the value of the carToRegister property.
     * 
     * @param value
     *     allowed object is
     *     {@link CarXml }
     *     
     */
    public void setCarToRegister(CarXml value) {
        this.carToRegister = value;
    }

}
